version: "3"

services:
  database:
    image: postgres:9.6-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER:-curator-dev}
      - POSTGRES_DB=${DB_DATABASE:-curator-dev}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
