# Generated by Django 2.2.24 on 2023-04-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curation_portal", "0014_auto_20230427_0324"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="ucsc_session_name_grch38",
            field=models.CharField(blank=True, max_length=1000, null=True),
        )
    ]
