# Generated by Django 2.2.24 on 2023-07-31 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curation_portal', '0016_auto_20230614_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='curationresult',
            name='curator_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
