# Generated by Django 2.2.24 on 2023-08-15 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curation_portal', '0017_auto_20230726_0322'),
        ('curation_portal', '0017_curationresult_curator_comments'),
    ]

    operations = [
    ]
