# Generated by Django 2.2.24 on 2023-07-28 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("curation_portal", "0018_auto_20230726_0632"),
    ]

    operations = [
        migrations.RenameField(
            model_name="variant",
            old_name="sampleIDs",
            new_name="sample_ids",
        ),
    ]
