# Generated by Django 2.2.24 on 2023-08-16 07:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curation_portal', '0018_merge_20230815_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='reads',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2000), blank=True, null=True, size=None),
        ),
    ]
